package visualization;

import client.Client;
import travel.Trip;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

public class DashboardGenerator {

    public static void generateDashboard(Client[] clients, int clientCount, Trip[] trips, int tripCount) throws IOException {
        ensureDir("output/dashboard");
        ensureDir("output/charts"); // required folder by spec

        writeCss("output/dashboard/styles.css");
        writeHtml("output/dashboard/dashboard.html", clients, clientCount, trips, tripCount);
    }

    private static void writeCss(String path) throws IOException {
        PrintWriter out = new PrintWriter(new FileWriter(path));
        out.println("body{font-family:Arial, sans-serif; margin:24px;}");
        out.println("h1{margin-bottom:6px;}");
        out.println(".card{border:1px solid #ddd; padding:16px; border-radius:10px; margin:14px 0;}");
        out.println(".bar{height:16px; background:#4a90e2; border-radius:6px; display:inline-block;}");
        out.println(".row{margin:8px 0;}");
        out.println(".muted{color:#666; font-size:12px;}");
        out.close();
    }

    private static void writeHtml(String path, Client[] clients, int clientCount, Trip[] trips, int tripCount) throws IOException {
        PrintWriter out = new PrintWriter(new FileWriter(path));

        out.println("<!DOCTYPE html><html><head><meta charset='utf-8'/>");
        out.println("<title>SmartTravel Dashboard</title>");
        out.println("<link rel='stylesheet' href='styles.css'/>");
        out.println("</head><body>");

        out.println("<h1>SmartTravel Dashboard</h1>");
        out.println("<div class='muted'>Generated by DashboardGenerator (no external libs)</div>");

        out.println("<div class='card'>");
        out.println("<h2>Counts</h2>");
        out.println("<div class='row'>Clients: " + clientCount + "</div>");
        out.println("<div class='row'>Trips: " + tripCount + "</div>");
        out.println("</div>");

        out.println("<div class='card'>");
        out.println("<h2>Client Spending</h2>");
        double max = 0.0;
        for (int i = 0; i < clientCount; i++) {
            if (clients[i] != null && clients[i].getAmountSpent() > max) max = clients[i].getAmountSpent();
        }
        if (max <= 0) max = 1;

        for (int i = 0; i < clientCount; i++) {
            if (clients[i] == null) continue;
            double spent = clients[i].getAmountSpent();
            int width = (int) Math.round((spent / max) * 300.0);

            out.println("<div class='row'>");
            out.println("<b>" + clients[i].getClientId() + "</b> " + clients[i].getFirstName() + " " + clients[i].getLastName() +
                    " — $" + String.format("%.2f", spent) + "<br/>");
            out.println("<span class='bar' style='width:" + width + "px'></span>");
            out.println("</div>");
        }
        out.println("</div>");

        out.println("<div class='card'>");
        out.println("<h2>Trips Summary</h2>");
        for (int i = 0; i < tripCount; i++) {
            Trip t = trips[i];
            if (t == null) continue;
            out.println("<div class='row'><b>" + t.getTripId() + "</b> — " + t.getDestination() +
                    " (" + t.getDurationInDays() + " days), base $" + String.format("%.2f", t.getBasePrice()) + "</div>");
        }
        out.println("</div>");

        out.println("</body></html>");
        out.close();
    }

    private static void ensureDir(String dir) {
        File f = new File(dir);
        if (!f.exists()) f.mkdirs();
    }
}