// -----------------------------------------------------
// Assignment 2
// Class: Flight
// Written by: Yousef Yousef (40299095) & Hamza Shadeed (403
// -----------------------------------------------------

package travel;

import exceptions.InvalidTransportDataException;

/** Core Flight entity in the SmartTravel system */
public class Flight extends Transportation {

    private String airlineName;
    private double luggageAllowanceKg;

    /** Default constructor: base fare = 350 */
    public Flight() {
        super();
        this.airlineName = "Unknown";
        this.luggageAllowanceKg = 0.0;
        try {
            setBaseFare(350.0);
        } catch (InvalidTransportDataException ignore) {
        }
    }

    /** constructor: base fare = 350 */
    public Flight(String companyName, String departureCity, String arrivalCity, String airlineName, double luggageAllowanceKg)
            throws InvalidTransportDataException {
        super(companyName, departureCity, arrivalCity);
        setAirlineName(airlineName);
        setLuggageAllowanceKg(luggageAllowanceKg);
        setBaseFare(350.0);
    }

    /** constructor (base fare comes from CSV) */
    public Flight(String companyName, String departureCity, String arrivalCity, String airlineName,
                  double baseFare, double luggageAllowanceKg) throws InvalidTransportDataException {
        super(companyName, departureCity, arrivalCity, baseFare);
        setAirlineName(airlineName);
        setLuggageAllowanceKg(luggageAllowanceKg);
    }

    /** load-time constructor (explicit ID) */
    public Flight(String transportId, String companyName, String departureCity, String arrivalCity, String airlineName,
                  double baseFare, double luggageAllowanceKg) throws InvalidTransportDataException {
        super(transportId, companyName, departureCity, arrivalCity, baseFare);
        setAirlineName(airlineName);
        setLuggageAllowanceKg(luggageAllowanceKg);
    }

    /** Copy constructor: new ID generated by super copy */
    public Flight(Flight other) {
        super(other);
        this.airlineName = other.airlineName;
        this.luggageAllowanceKg = other.luggageAllowanceKg;
    }


    /** Validation & Accessors */
    private static boolean isBlank(String s) {
        return s == null || s.trim().isEmpty();
    }

    public String getAirlineName() {
        return airlineName;
    }

    public void setAirlineName(String airlineName) throws InvalidTransportDataException {
        if (isBlank(airlineName)) {
            throw new InvalidTransportDataException("airlineName cannot be empty.");
        }
        this.airlineName = airlineName.trim();
    }

    public double getLuggageAllowanceKg() {
        return luggageAllowanceKg;
    }

    public void setLuggageAllowanceKg(double luggageAllowanceKg) throws InvalidTransportDataException {
        // A2 rule: luggage allowance >= 0
        if (luggageAllowanceKg < 0) {
            throw new InvalidTransportDataException("luggageAllowanceKg cannot be negative.");
        }
        this.luggageAllowanceKg = luggageAllowanceKg;
    }

    /** base fare + excess luggage fees */
    @Override
    public double calculateCost(int numberOfDays) {
        double base = getBaseFare();
        double baggageFee = 0.0;

        if (luggageAllowanceKg > 20.0) {
            baggageFee = (luggageAllowanceKg - 20.0) * 10.0;
        }
        return base + baggageFee;
    }

    @Override
    public boolean equals(Object oth) {
        if (!super.equals(oth)) return false;
        if (!(oth instanceof Flight)) return false;

        Flight other = (Flight) oth;

        if (airlineName == null) {
            if (other.airlineName != null) return false;
        } else if (!airlineName.equals(other.airlineName)) {
            return false;
        }

        return Double.compare(luggageAllowanceKg, other.luggageAllowanceKg) == 0;
    }

    /** Provides a clean summary for display */
    @Override
    public String toString() {
        return "Flight{transportId='" + getTransportId() + "', companyName='" + getCompanyName() +
                "', departureCity='" + getDepartureCity() + "', arrivalCity='" + getArrivalCity() +
                "', airlineName='" + airlineName + "', baseFare=" + getBaseFare() +
                ", luggageAllowanceKg=" + luggageAllowanceKg + "}";
    }

    /** EQUALS */
    @Override
    public boolean equals(Object obj) {
        if (!super.equals(obj)) return false;
        Flight other = (Flight) obj;

        if (airlineName == null && other.airlineName != null) return false;
        if (airlineName != null && !airlineName.equals(other.airlineName)) return false;

        if (Double.compare(luggageAllowanceKg, other.luggageAllowanceKg) != 0) return false;

        return true;
    }

    @Override
    public String getType() { return "Flight"; }
}